RestaurantCoreApp/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RestaurantCoreApp.Data;
using RestaurantCoreApp.Models;
using RestaurantCoreApp.Utility;

namespace RestaurantCoreApp.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
	[Area("Admin")]
    public class CategoryController : Controller
    {
		private readonly ApplicationDbContext _db;

		public CategoryController(ApplicationDbContext db)
		{
			_db = db;
		}
		
		//GET 
        public async Task<IActionResult> Index()
        {
            return View(await _db.Category.ToListAsync());
        }

		//GET - CREATE
		public IActionResult Create()
		{
			return View();
		}

		//POST - CREATE
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(Category category)
		{
			if (ModelState.IsValid)
			{
				//if valid
				_db.Category.Add(category);
				await _db.SaveChangesAsync();

				return RedirectToAction(nameof(Index));
			}
			return View(category);
		}

		//GET - EDIT
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var category = await _db.Category.FindAsync(id);
			if (category == null)
			{
				return NotFound();
			}
			return View(category);
		}

		//POST - EDIT
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(Category category)
		{
			if (ModelState.IsValid)
			{
				_db.Update(category);
				await _db.SaveChangesAsync();

				return RedirectToAction(nameof(Index));
			}
			return View(category);
		}

		//GET - DELETE
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var category = await _db.Category.FindAsync(id);
			if (category == null)
			{
				return NotFound();
			}
			return View(category);
		}

		//POST - DELETE
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int? id)
		{
			var category = await _db.Category.FindAsync(id);
			if (category == null)
			{
				return View();
			}
			_db.Category.Remove(category);
			await _db.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		//GET - Details
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var category = await _db.Category.FindAsync(id);
			if (category == null)
			{
				return NotFound();
			}
			return View(category);
		}
	}
}

RestaurantCoreApp/Areas/Admin/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RestaurantCoreApp.Data;
using RestaurantCoreApp.Models;
using RestaurantCoreApp.Utility;

namespace RestaurantCoreApp.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class CouponController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CouponController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _db.Coupon.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Coupon coupons)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream())
                    {
                        using(var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray();
                        }
                    }
                    coupons.Picture = p1;
                }
                _db.Coupon.Add(coupons);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(coupons);
        }


        //GET Edit Coupon
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var coupon = await _db.Coupon.SingleOrDefaultAsync(m => m.Id == id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Coupon coupons)
        {
            if (coupons.Id == 0)
            {
                return NotFound();
            }

            var couponFromDb = await _db.Coupon.Where(c => c.Id == coupons.Id).FirstOrDefaultAsync();

            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream())
                    {
                        using (var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray();
                        }
                    }
                    couponFromDb.Picture = p1;
                }
                couponFromDb.MinimumAmount = coupons.MinimumAmount;
                couponFromDb.Name = coupons.Name;
                couponFromDb.Discount = coupons.Discount;
                couponFromDb.CouponType = coupons.CouponType;
                couponFromDb.isActive = coupons.isActive;

                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coupons);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coupon = await _db.Coupon
                .FirstOrDefaultAsync(m => m.Id == id);
            if (coupon == null)
            {
                return NotFound();
            }

            return View(coupon);
        }

        //GET Delete Coupon
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var coupon = await _db.Coupon.SingleOrDefaultAsync(m => m.Id == id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var coupons = await _db.Coupon.SingleOrDefaultAsync(m => m.Id == id);
            _db.Coupon.Remove(coupons);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /*
         //POST - CREATE
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(Category category)
		{
			if (ModelState.IsValid)
			{
				//if valid
				_db.Category.Add(category);
				await _db.SaveChangesAsync();

				return RedirectToAction(nameof(Index));
			}
			return View(category);
		}
         */
    }
}

RestaurantCoreApp/Areas/Admin/Controllers/SubCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestaurantCoreApp.Data;
using RestaurantCoreApp.Models;
using RestaurantCoreApp.Models.ViewModels;
using RestaurantCoreApp.Utility;

namespace RestaurantCoreApp.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class SubCategoryController : Controller
    {
		private readonly ApplicationDbContext _db;

		[TempData]
		public string StatusMessage { get; set; }

		public SubCategoryController(ApplicationDbContext db)
		{
			_db = db;
		}

		//GET Index
		public async Task<IActionResult> Index()
		{
			var subCategories = await _db.SubCategory.Include(s=>s.Category).ToListAsync();
			return View(subCategories);
		}

		// GET- CREATE
		public async Task<IActionResult> Create()
		{
			SubCategoryAndCategoryViewModel model = new SubCategoryAndCategoryViewModel()
			{
				CategoryList = await _db.Category.ToListAsync(),
				SubCategory = new Models.SubCategory(),
				SubCategoryList = await _db.SubCategory.OrderBy(p=>p.Name).Select(p=>p.Name).Distinct().ToListAsync()
			};

			return View(model);
		}

		//POST - CREATE
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(SubCategoryAndCategoryViewModel model)
		{
			if (ModelState.IsValid)
			{
				var doesSubCategoryExists = _db.SubCategory.Include(s => s.Category).Where(s => s.Name == model.SubCategory.Name && s.Category.Id == model.SubCategory.CategoryId);

				if (doesSubCategoryExists.Count() > 0)
				{
					//Error
					StatusMessage = "Error : Sub Category exists under " + doesSubCategoryExists.First().Category.Name + " category. Please use another name. ";
				}
				else
				{
					_db.SubCategory.Add(model.SubCategory);
					await _db.SaveChangesAsync();
					return RedirectToAction(nameof(Index));
				}

			}
			SubCategoryAndCategoryViewModel modelVm = new SubCategoryAndCategoryViewModel()
			{
				CategoryList = await _db.Category.ToListAsync(),
				SubCategory = model.SubCategory,
				SubCategoryList = await _db.SubCategory.OrderBy(p => p.Name).Select(p => p.Name).ToListAsync(),
				StatusMessage = StatusMessage
			};
			return View(modelVm);
		}

		[ActionName("GetSubCategory")]
		public async Task<IActionResult> GetSubCategory(int id)
		{
			List<SubCategory> subCategories = new List<SubCategory>();
			subCategories = await (from subCategory in _db.SubCategory
							 where subCategory.CategoryId == id
							 select subCategory).ToListAsync();
			return Json(new SelectList(subCategories, "Id", "Name"));
		}

		// GET- EDIT
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var subCategory = await _db.SubCategory.SingleOrDefaultAsync(m => m.Id == id);

			if (subCategory == null)
			{
				return NotFound();
			}

			SubCategoryAndCategoryViewModel model = new SubCategoryAndCategoryViewModel()
			{
				CategoryList = await _db.Category.ToListAsync(),
				SubCategory = subCategory,
				SubCategoryList = await _db.SubCategory.OrderBy(p => p.Name).Select(p => p.Name).Distinct().ToListAsync()
			};

			return View(model);
		}

		//POST - EDIT
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(SubCategoryAndCategoryViewModel model)
		{
			if (ModelState.IsValid)
			{
				var doesSubCategoryExists = _db.SubCategory.Include(s => s.Category).Where(s => s.Name == model.SubCategory.Name && s.Category.Id == model.SubCategory.CategoryId);

				if (doesSubCategoryExists.Count() > 0)
				{
					//Error
					StatusMessage = "Error : Sub Category exists under " + doesSubCategoryExists.First().Category.Name + " category. Please use another name. ";
				}
				else
				{
					var subCatFromDb = await _db.SubCategory.FindAsync(model.SubCategory.Id);
					subCatFromDb.Name = model.SubCategory.Name;

					await _db.SaveChangesAsync();
					return RedirectToAction(nameof(Index));
				}

			}
			SubCategoryAndCategoryViewModel modelVm = new SubCategoryAndCategoryViewModel()
			{
				CategoryList = await _db.Category.ToListAsync(),
				SubCategory = model.SubCategory,
				SubCategoryList = await _db.SubCategory.OrderBy(p => p.Name).Select(p => p.Name).ToListAsync(),
				StatusMessage = StatusMessage
			};
			return View(modelVm);
		}


		// GET- DETAILS
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var subCategory = await _db.SubCategory.Include(s => s.Category).SingleOrDefaultAsync(m => m.Id == id);

			if (subCategory == null)
			{
				return NotFound();
			}

			return View(subCategory);
		}

		// GET- DELETE
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var subCategory = await _db.SubCategory.Include(s => s.Category).SingleOrDefaultAsync(m => m.Id == id);

			if (subCategory == null)
			{
				return NotFound();
			}

			return View(subCategory);
		}

		//POST - DELETE
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int? id)
		{
			var subCategory = await _db.SubCategory.Include(s => s.Category).SingleOrDefaultAsync(m => m.Id == id);
			if(subCategory == null)
			{
				return View();
			}
			_db.SubCategory.Remove(subCategory);
			await _db.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		/*
		 //POST - DELETE
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int? id)
		{
			var category = await _db.Category.FindAsync(id);
			if (category == null)
			{
				return View();
			}
			_db.Category.Remove(category);
			await _db.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}
		 */


	}
}

RestaurantCoreApp/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RestaurantCoreApp.Data;
using RestaurantCoreApp.Utility;

namespace RestaurantCoreApp.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            return View(await _db.ApplicationUser.Where(u=>u.Id != claim.Value).ToListAsync());
        }

        public async Task<IActionResult> Lock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);

            if (applicationUser == null)
            {
                return NotFound();
            }

            applicationUser.LockoutEnd = DateTime.Now.AddMinutes(2);

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UnLock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);

            if (applicationUser == null)
            {
                return NotFound();
            }

            applicationUser.LockoutEnd = DateTime.Now;

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

RestaurantCoreApp/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Create" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

RestaurantCoreApp/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> &nbsp; Create New</a>
</p>

RestaurantCoreApp/Views/Shared/_DeleteAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model" value="Delete" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

RestaurantCoreApp/Views/Shared/_DetailsAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <a asp-action="Edit" class="btn btn-info form-control" asp-route-Id="@Model">Edit</a>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

RestaurantCoreApp/Views/Shared/_EditAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" asp-route-id="@Model" value="Update" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

RestaurantCoreApp/Views/Shared/_Layout.cshtml
@using RestaurantCoreApp.Utility
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestaurantCoreApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    <img src="~/images/mild.png" />
                    <label class="text-info" style="cursor:pointer">Restaurant App</label>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
                                    Content Managment
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="SubCategory" asp-action="Index">Sub Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="MenuItem" asp-action="Index">MenuItem</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Coupon" asp-action="Index">Coupons</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                                </div>
                            </li>
                        }

                        @if (HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShoppingCartCount) != null)
                        {
                            <li style="color:white">
                                <a href="#" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShoppingCartCount);
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            </li>
                        }
                        else
                        {
                            <li style="color:white">
                                <a href="#" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                </a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color: #343a40;">
        <div class="container">
            &copy; 2019 - RestaurantCoreApp
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

RestaurantCoreApp/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

RestaurantCoreApp/Views/Shared/_TableButtonPartial.cshtml
@model  int

    <td style="width:150px">
        <div class="btn-group" role="group">
            <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
                <i class="fas fa-edit"></i>
            </a>
        
            <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
                <i class="fas fa-list-alt"></i>
            </a>
       
            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
                <i class="fas fa-trash-alt"></i>
            </a>
        </div>
    </td>

RestaurantCoreApp/Views/Shared/_ThumbnailAreaPartial.cshtml
@model  IEnumerable<MenuItem>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@if (Model.Count() > 0)
{
    <div class="col-12 post @Model.FirstOrDefault().Category.Name.Replace(" ",string.Empty) menu-restaurant">
        <div class="row">
            <h3 class="text-success">@Model.FirstOrDefault().Category.Name</h3>
        </div>

        @foreach(var item in Model)
        {
            <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px;padding:10px">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <img src="@item.Image" width="99%" style="border-radius:5px;border:1px; solid #bbb9b9" />
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <label class="text-primary" style="font-size:21px;color:maroon">@item.Name</label>
                                @if (item.Spicyness == "1")
                                {
                                    <img src="~/images/mild.png" title="Mild" />
                                }
                                @if (item.Spicyness == "2")
                                {
                                    <img src="~/images/spicy.png" title="Spicy" />
                                }
                                @if (item.Spicyness == "3")
                                {
                                    <img src="~/images/verySpicy.png" title="Very Spicy" />
                                }
                            </div>
                            <div class="col-4 text-right" style="color:maroon">
                                <h4>$@item.Price</h4>
                            </div>
                        </div>

                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@Html.Raw(item.Description)</p>
                        </div>

                        <div class="col-md-3 col-sm-12 offset-md-9 text-center ">
                            <a asp-action="Details" class="btn btn-success form-control" asp-route-id="@item.Id">Details</a>
                        </div>
                    </div>
                    </div>
                </div>
        }
        <div class="p-4"></div>
    </div>
}